# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 00:46
from __future__ import unicode_literals

from django.db import migrations
import django_filepicker.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160425_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_url',
            field=django_filepicker.models.FPUrlField(default=1),
            preserve_default=False,
        ),
    ]
