# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 20:42
from __future__ import unicode_literals

from django.db import migrations
import django_filepicker.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image_url',
            field=django_filepicker.models.FPUrlField(blank=True, null=True),
        ),
    ]
