# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20160521_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
