# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-11 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_apns_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='available_money',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pending_money',
            field=models.FloatField(default=0.0),
        ),
    ]
