# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20160611_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='apns_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='paypal',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
