# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-26 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20160923_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawrequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
