# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-04 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20160926_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
