# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-04 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customuser_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='apt_suite_bldg',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='occupation',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='customuser',
            name='permanent_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='permanent_address_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='permanent_address_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='residence_status',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='suffix',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_annual_income',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='us_citizen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='work_phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zip_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
