# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-04 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20180504_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
