# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-04 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customuser_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_prized',
            field=models.BooleanField(default=False),
        ),
    ]
