# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-09 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20180508_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='total_annual_income',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
