# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 07:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('variable', 'Variable'), ('surge', 'Surge'), ('fixed', 'Fixed')], default='variable', max_length=50)),
                ('start_date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('min_reward', models.FloatField(default=0.0)),
                ('max_reward', models.FloatField(default=1.0)),
                ('redeemable_quantity', models.IntegerField(default=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50)),
                ('display_order', models.IntegerField(default=1)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.Business')),
            ],
        ),
    ]
