# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_offer_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
