# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_auto_20160609_0533'),
        ('offers', '0007_auto_20160604_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating1', to='businesses.Rating'),
        ),
    ]
