# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 00:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_receipt_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='surge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='surge_end',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='offer',
            name='surge_multiplier',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='offer',
            name='surge_start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='receipt',
            name='money_earned',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('variable', 'Variable'), ('fixed', 'Fixed')], default='fixed', max_length=50),
        ),
    ]
