# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 06:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_auto_20160612_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='variable_rewards',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
