# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_offer_variable_rewards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='end_date_time',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='start_date_time',
        ),
    ]
