# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 18:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0012_offer_minimum_spend_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-submit_time']},
        ),
        migrations.AlterField(
            model_name='offer',
            name='display_order',
            field=models.FloatField(default=3.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(50.0)]),
        ),
        migrations.AlterField(
            model_name='offer',
            name='max_reward',
            field=models.FloatField(default=0.25),
        ),
        migrations.AlterField(
            model_name='offer',
            name='min_reward',
            field=models.FloatField(default=0.25),
        ),
    ]
