# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-18 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0013_auto_20160730_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='details',
            field=models.TextField(default='', max_length=1200),
        ),
    ]
