# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django_filepicker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('receipt_rules', models.TextField(max_length=600)),
                ('featured_img', django_filepicker.models.FPUrlField()),
                ('logo_img', django_filepicker.models.FPUrlField()),
            ],
        ),
    ]
