# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_offer_featured'),
        ('businesses', '0004_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='receipt',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='offers.Receipt'),
        ),
    ]
