# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_rating_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='comments',
            field=models.TextField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='rating',
            name='would_return',
            field=models.BooleanField(default=True),
        ),
    ]
