# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_auto_20160617_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='receipt_rules',
            field=models.TextField(max_length=1200),
        ),
    ]
